version: "3"

services:
  frontend:
    env_file:
      - ./frontend/.env
    build:
      context: frontend
      dockerfile: Dockerfile
    image: prologueacr.azurecr.io/frontend:v4
    container_name: web
    restart: always
    ports:
      - 3000:3000
    labels:
      kompose.service.type: LoadBalancer

  backend-core:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    image: prologueacr.azurecr.io/backend-core:v4
    container_name: backend-core
    restart: always
    volumes:
      - ./backend/:/code/
    depends_on:
      - redis
      - worker
      - beat
    ports:
      - 5050:5050
    labels:
      kompose.service.type: LoadBalancer

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  worker:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    image: prologueacr.azurecr.io/worker:v4
    container_name: worker
    command: celery -A celery_worker worker -l info
    restart: always
    depends_on:
      - redis
    volumes:
      - ./backend/:/code/

  beat:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    image: prologueacr.azurecr.io/beat:v4
    container_name: beat
    command: celery -A celery_worker beat -l info
    restart: always
    depends_on:
      - redis
    volumes:
      - ./backend/:/code/

  flower:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    image: prologueacr.azurecr.io/flower:v4
    container_name: flower
    command: celery -A celery_worker flower -l info --port=5555
    restart: always
    volumes:
      - ./backend/:/code/
    depends_on:
      - redis
      - worker
      - beat
    ports:
      - 5555:5555
